image: Visual Studio 2022
build: off

branches:
  only:
    - main

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node 18
  - npm install
  - npm install -g vite

test_script:
  - npm run build

artifacts:
  - path: dist\**
    name: app-build

# Правильная секция деплоя
deploy:
  provider: GitHub
  artifact: app-build  # Должно совпадать с именем в artifacts
  draft: false
  description: "Automatic deployment"
  auth_token:
    secure: Frontend-diplom  # Зашифруйте в настройках AppVeyor
  on:
    branch: main