image: Visual Studio 2022
build: off

branches:
  only:
    - main

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node 18
  - npm install
  - npm install -g vite

test_script:
  - npm run build

artifacts:
  - path: dist\**
    name: app-build

deployment:
  provider: GitHub
  artifact: app-build
  draft: false
  auth_token:
    secure: Frontend-diplom
  on:
    branch: main